name: xnet-ray-tracing
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - pyyaml
  - matplotlib
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - scikit-learn
  - notebook
  - enlighten
  - plotly
  - seaborn
  - tqdm
